# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf2d2d487ad360dce17dcc4f1101c8b6ba6e62565ba8469256e2ce6a5de79bd41eab5a9e2364834a02f89c1189c1b8984e023f306873b64eb1b64af1b9755beb

test:
  secret_key_base: 4872ee5a4bf555e583c7d4467294c7dc4e89a5d5066503918cfe414ca7e7cc97aa3bf9de84160a8abef8726814fe9f53195d442221e230fea93a11acde327f80

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
